CREATE DATABASE CHARAN;
USE CHARAN;
CREATE TABLE STUDENTS3 (SNO INT,NAME VARCHAR(30) ,ID INT);
SELECT * FROM STUDENTS3 ;
ALTER TABLE STUDENTS3
ADD CGPA int;
ALTER TABLE STUDENTS3
RENAME COLUMN CGPA TO date_of_birth;
ALTER TABLE STUDENTS3
DROP COLUMN date_of_birth;
INSERT INTO STUDENTS3 VALUES(1,'CHARAN',6455),(2,'HELLO',467);
SELECT * FROM STUDENTS3 ;
TRUNCATE TABLE STUDENTS3;
DROP TABLE STUDENTS3;
