

-- Create tables
CREATE TABLE Categories (
    CategoryID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryName VARCHAR2(100) NOT NULL
);

CREATE TABLE Books (
    BookID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR2(255) NOT NULL,
    ISBN VARCHAR2(20) UNIQUE,
    CategoryID NUMBER,
    Publisher VARCHAR2(100),
    YearPublished NUMBER(4),
    CopiesAvailable NUMBER DEFAULT 1,
    CONSTRAINT fk_books_category FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);

CREATE TABLE Authors (
    AuthorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(100),
    LastName VARCHAR2(100)
);

CREATE TABLE BookAuthors (
    BookID NUMBER,
    AuthorID NUMBER,
    CONSTRAINT pk_bookauthors PRIMARY KEY (BookID, AuthorID),
    CONSTRAINT fk_bookauthors_book FOREIGN KEY (BookID) REFERENCES Books(BookID),
    CONSTRAINT fk_bookauthors_author FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID)
);

CREATE TABLE Users (
    UserID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(100),
    LastName VARCHAR2(100),
    UserType VARCHAR2(20) CHECK (UserType IN ('Student','Staff')),
    Email VARCHAR2(150) UNIQUE
);

CREATE TABLE Loans (
    LoanID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookID NUMBER,
    UserID NUMBER,
    LoanDate DATE NOT NULL,
    DueDate DATE NOT NULL,
    ReturnDate DATE,
    CONSTRAINT fk_loans_book FOREIGN KEY (BookID) REFERENCES Books(BookID),
    CONSTRAINT fk_loans_user FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- Insert data
INSERT INTO Categories (CategoryName) VALUES ('Computer Science');
INSERT INTO Categories (CategoryName) VALUES ('Mathematics');
INSERT INTO Categories (CategoryName) VALUES ('Literature');
INSERT INTO Categories (CategoryName) VALUES ('Physics');
INSERT INTO Categories (CategoryName) VALUES ('History');

INSERT INTO Authors (FirstName, LastName) VALUES ('Donald', 'Knuth');
INSERT INTO Authors (FirstName, LastName) VALUES ('J.K.', 'Rowling');
INSERT INTO Authors (FirstName, LastName) VALUES ('Stephen', 'Hawking');
INSERT INTO Authors (FirstName, LastName) VALUES ('Isaac', 'Newton');
INSERT INTO Authors (FirstName, LastName) VALUES ('George', 'Orwell');

INSERT INTO Books (Title, ISBN, CategoryID, Publisher, YearPublished, CopiesAvailable)
VALUES ('The Art of Computer Programming', '9780201896831', 1, 'Addison-Wesley', 1997, 3);

INSERT INTO Books (Title, ISBN, CategoryID, Publisher, YearPublished, CopiesAvailable)
VALUES ('Harry Potter and the Sorcerer''s Stone', '9780747532699', 3, 'Bloomsbury', 1997, 5);

INSERT INTO Books (Title, ISBN, CategoryID, Publisher, YearPublished, CopiesAvailable)
VALUES ('A Brief History of Time', '9780553380163', 4, 'Bantam', 1988, 4);

INSERT INTO Books (Title, ISBN, CategoryID, Publisher, YearPublished, CopiesAvailable)
VALUES ('Principia Mathematica', '9780521626064', 2, 'Cambridge University Press', 1687, 2);

INSERT INTO Books (Title, ISBN, CategoryID, Publisher, YearPublished, CopiesAvailable)
VALUES ('1984', '9780451524935', 3, 'Secker & Warburg', 1949, 6);

INSERT INTO BookAuthors VALUES (1, 1);
INSERT INTO BookAuthors VALUES (2, 2);
INSERT INTO BookAuthors VALUES (3, 3);
INSERT INTO BookAuthors VALUES (4, 4);
INSERT INTO BookAuthors VALUES (5, 5);

INSERT INTO Users (FirstName, LastName, UserType, Email)
VALUES ('Alice', 'Johnson', 'Student', 'alice.johnson@univ.edu');
INSERT INTO Users (FirstName, LastName, UserType, Email)
VALUES ('Bob', 'Smith', 'Student', 'bob.smith@univ.edu');
INSERT INTO Users (FirstName, LastName, UserType, Email)
VALUES ('Clara', 'Evans', 'Staff', 'clara.evans@univ.edu');
INSERT INTO Users (FirstName, LastName, UserType, Email)
VALUES ('David', 'Brown', 'Student', 'david.brown@univ.edu');

INSERT INTO Loans (BookID, UserID, LoanDate, DueDate, ReturnDate)
VALUES (1, 1, TO_DATE('2025-10-01', 'YYYY-MM-DD'), TO_DATE('2025-10-15', 'YYYY-MM-DD'), TO_DATE('2025-10-14', 'YYYY-MM-DD'));
INSERT INTO Loans (BookID, UserID, LoanDate, DueDate, ReturnDate)
VALUES (2, 2, TO_DATE('2025-10-20', 'YYYY-MM-DD'), TO_DATE('2025-11-03', 'YYYY-MM-DD'), NULL);
INSERT INTO Loans (BookID, UserID, LoanDate, DueDate, ReturnDate)
VALUES (3, 3, TO_DATE('2025-09-15', 'YYYY-MM-DD'), TO_DATE('2025-09-30', 'YYYY-MM-DD'), TO_DATE('2025-09-28', 'YYYY-MM-DD'));
INSERT INTO Loans (BookID, UserID, LoanDate, DueDate, ReturnDate)
VALUES (4, 1, TO_DATE('2025-11-01', 'YYYY-MM-DD'), TO_DATE('2025-11-15', 'YYYY-MM-DD'), NULL);

COMMIT;
